### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#30]
It's time to release this package!  Before we do, there are a few more tasks left:

- [x] Add more content to the website:
    - [x] Introduction (adapt from README.md)
    - [x] Installation
    - [x] Link in the FAQ
    - [x] Add screenshots
    - [ ] Jim: review user guide
    - [x] Add a gallery?  (Maybe too ambitious for right now)
- [x] Add website theme (colors, fixing logo spacing)
- [x] Add `interact()` function
- [x] Finalize the name (it's now or never!)

Either before or soon after release, we should also:
- [x] Add links from parambokeh and paramnb pointing to Panel
- [x] Replace parambokeh and paramnb examples on holoviews.org and pyviz.org

Please edit these lists to add anything I missed.

**Comment by philippjfr** [comment]
@jbednar Can this be closed or are you still reviewing?
