### ISSUE TITLE
v0.7.0 Task List

### ISSUE THREAD

**Issue by philippjfr** [pyviz/panel#754]
- [x] Move thumbnails on homepage up
- [x] Update FAQ after reviewing webinar questions (@jbednar)
- [x] Update Getting Started to use the room occupancy (https://anaconda.org/jbednar/project/Room_Occupancy) (issue https://github.com/pyviz/panel/issues/510)
- [x] Check Overview and add new methods/functions (e.g. Voila deployment?)
- [x] Add initial deploy docs
- [x] Update Widgets with newest widget types
- [x] Look at fixing Parameters HTML/CSS issues
- [x] Add param.DataFrame example
- [x] Improve "Registering a watcher" example in linking (nothing shows up on website)
- [x] Add new examples to Gallery
- [x] Update thumbnails on Homepage
- [ ] Update gallery deployments on AE5
- [x] Finish Comparisons PR (@jbednar)
- [ ] FAQ: Point to tips for speeding up Panel under "What performance limitations does Panel have?"
- [ ] FAQ: Explain embedding better in "require a live Python process for deployment"
